Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -1,9 +1,6 @@
 name: Minecraft Docker Image CI
 
-# 触发配置
 on:
-  schedule:
-    - cron: '0 0 */3 * *'
   workflow_dispatch:
     inputs:
       LATEST_VERSION:
@@ -13,132 +10,27 @@ on:
         type: string
 
 jobs:
-  build:
+  get_forge_version:
     runs-on: ubuntu-latest
-
     steps:
-    - uses: actions/checkout@v4
-
-    # Step 1: 设置Docker Buildx
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v2
-
-    # Step 2: 为多平台构建安装QEMU
-    - name: Set up QEMU
-      uses: docker/setup-qemu-action@v3
-
-    # Step 3: 登录Docker Hub
-    - name: Login to Docker Hub
-      uses: docker/login-action@v3
-      with:
-        username: ${{ secrets.DOCKER_USERNAME }}
-        password: ${{ secrets.DOCKER_PASSWORD }}
-
-    # Step 4: 获取最新的Minecraft版本信息
-    - name: Fetch Minecraft version info
-      id: version_info
-      run: |
-        # Minecraft版本信息地址
-        VERSION_MANIFEST_URL="https://launchermeta.mojang.com/mc/game/version_manifest.json"
-        if [ -n "${{ github.event.inputs.LATEST_VERSION }}" ]; then
-          # 使用手动指定的版本
-          LATEST_VERSION=${{ github.event.inputs.LATEST_VERSION }}
-          VERSION_URL=$(curl -s $VERSION_MANIFEST_URL | jq -r --arg LATEST_VERSION "$LATEST_VERSION" '.versions[] | select(.id==$LATEST_VERSION and .type=="release") | .url')
-          echo "VERSION_URL=$VERSION_URL" >> $GITHUB_ENV
-        else
-          # 自动获取最新版本信息
-          LATEST_VERSION=$(curl -s $VERSION_MANIFEST_URL | jq -r '.versions[] | select(.type=="release") | .id' | head -n 1)
-          VERSION_URL=$(curl -s $VERSION_MANIFEST_URL | jq -r --arg LATEST_VERSION "$LATEST_VERSION" '.versions[] | select(.id==$LATEST_VERSION and .type=="release") | .url')
-          echo "VERSION_URL=$VERSION_URL" >> $GITHUB_ENV
-        fi
-        echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
-
-    # Step 5: 检查版本是否更新
-    - name: Check if version is updated
-      id: check_version
-      run: |
-        # 检查是否手动输入了 LATEST_VERSION
-        if [ -z "${{ github.event.inputs.LATEST_VERSION }}" ]; then
-          # 尝试从`last_built_version.txt`中获取版本号
-          if [ -f last_built_version.txt ]; then
-            LAST_BUILT_VERSION=$(cat last_built_version.txt)
-          else
-            LAST_BUILT_VERSION="none"
+      - name: 获取Forge版本信息
+        run: |
+          url="https://files.minecraftforge.net/net/minecraftforge/forge/"
+          response=$(curl -s -f "$url")
+          if [ $? -ne 0 ]; then
+            echo "Failed to retrieve Forge version information"
+            exit 1
           fi
-          # 检查是否需要继续构建
-          if [ "$LAST_BUILT_VERSION" = "none" ]; then
-            # 没有旧版本时继续构建
-            echo "BUILD_NEEDED=true" >> $GITHUB_ENV
-          elif [ "$LATEST_VERSION" \> "$LAST_BUILT_VERSION" ]; then
-            # 如果新版本大于旧版本则继续构建
-            echo "BUILD_NEEDED=true" >> $GITHUB_ENV
-          else
-            # 如果新版本不大于旧版本则跳过构建
-            echo "BUILD_NEEDED=false" >> $GITHUB_ENV
+          minecraft_version=${{ github.event.inputs.LATEST_VERSION }}
+          latest_forge_version=$(echo "$response" | grep -oP "(?<=${minecraft_version}/).*?(?=/)" | sort -V | tail -1)
+          if [ -z "$latest_forge_version" ]; then
+            echo "No Forge version found for Minecraft ${minecraft_version}"
+            exit 1
           fi
-        else
-          # 手动输入版本则直接构建
-          echo "BUILD_NEEDED=true" >> $GITHUB_ENV
-        fi
-
-    # Step 6: 获取server.jar下载URL
-    - name: Fetch server.jar download URL
-      id: server_download_url
-      if: env.BUILD_NEEDED == 'true'
-      run: |
-        SERVER_URL=$(curl -s $VERSION_URL | jq -r '.downloads.server.url')
-        echo "SERVER_URL=$SERVER_URL" >> $GITHUB_ENV
-
-    # Step 7: 下载 server.jar
-    - name: Download server.jar
-      if: env.BUILD_NEEDED == 'true'
-      run: |
-        curl -fSL -o server.jar "$SERVER_URL"
-
-    # Step 8: 生成随机RCON密码
-    - name: Generate random RCON password
-      if: env.BUILD_NEEDED == 'true'
-      id: generate_password
-      run: |
-        RCON_PASSWORD=$(openssl rand -base64 30 | tr -dc 'A-Za-z0-9' | head -c 30)
-        echo "RCON_PASSWORD=$RCON_PASSWORD" >> $GITHUB_ENV
-
-    # Step 9: 将随机生成的密码写入 server.properties
-    - name: Update server.properties with RCON password
-      if: env.BUILD_NEEDED == 'true'
-      run: |
-        sed -i '/^rcon.password=/c\rcon.password=${{ env.RCON_PASSWORD }}' server.properties
-
-    # Step 10: 准备 Docker 镜像标签
-    - name: Prepare Docker tags
-      id: prepare_tags
-      if: env.BUILD_NEEDED == 'true'
-      run: |
-        if [ -n "${{ github.event.inputs.LATEST_VERSION }}" ]; then
-          echo "TAGS=fc6a1b03/minecraft-server:${{ github.event.inputs.LATEST_VERSION }}" >> $GITHUB_ENV
-        else
-          echo "TAGS=fc6a1b03/minecraft-server:latest,fc6a1b03/minecraft-server:${{ env.LATEST_VERSION }}" >> $GITHUB_ENV
-        fi
-    
-    # Step 11: 为多种架构构建和推送Docker镜像
-    - name: Build and push Docker image
-      if: env.BUILD_NEEDED == 'true'
-      uses: docker/build-push-action@v5
-      with:
-        context: .
-        push: true
-        tags: ${{ env.TAGS }}
-        platforms: linux/amd64,linux/arm64
-
-    # Step 12: 更新记录的最后构建版本
-    - name: Update last built version
-      if: env.BUILD_NEEDED == 'true' && github.event.inputs.LATEST_VERSION == ''
-      run: |
-        echo $LATEST_VERSION > last_built_version.txt
-        git config --global user.email "github-actions[bot]@users.noreply.github.com"
-        git config --global user.name "github-actions[bot]"
-        git add last_built_version.txt
-        git commit -m "Update last built version to $LATEST_VERSION"
-        git push --force
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          latest_forge_url="${url}${minecraft_version}/${latest_forge_version}/forge-${minecraft_version}-${latest_forge_version}-installer.jar"
+          echo "最新Forge版本下载链接：${latest_forge_url=${latest_forge_url}"
+        shell: bash
+      - name: 输出最新Forge版本下载链接
+        run: |
+          echo "最新Forge版本下载链接：${latest_forge_url}"
+        shell: bash
